# Generated by Django 5.0.3 on 2024-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('course', models.CharField(max_length=40)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
