# Generated by Django 5.0.3 on 2024-03-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pendingfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regis_stu',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
    ]
