# Generated by Django 5.0.3 on 2024-03-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_regis_stu_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingfee',
            old_name='first_installment',
            new_name='paid_fees',
        ),
        migrations.RenameField(
            model_name='pendingfee',
            old_name='name',
            new_name='stu_name',
        ),
    ]
